services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: database_name
      MARIADB_USER: user
      MARIADB_PASSWORD: resu
    volumes:
      - ./docker/db:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8080:8080