services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
  # Used to create another serive exemple for a DB
  # redis:
    # image: "redis:alpine"