name: working-workflow
run-name: ${{ github.actor }} is building - testing - deploying
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            /home/runner/.cache/cypress
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npm run build
  test:
    runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v3
        - uses: actions/cache@v3
          with:
            path: |
              node_modules
              /home/runner/.cache/cypress
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        - run: npm run e2e:headless
        - uses: actions/upload-artifact@v3
          with:
            name: e2e-video
            path: cypress/videos/
  # deploy:
  #   runs-on: ubuntu-latest
  #     steps:
  #     - uses: actions/checkout@v2
  #     - uses: tzzs/server-shell@v3                # action to connect to server via SSH
  #       with:                                     # can find secrets.vars in github/repo/Settings > Secrets and variables
  #         PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}  # is my local private ssh key for my ssh connection
  #         USERNAME: ${{secrets.SSH_USER}}
  #         IP: ${{secrets.HOST}}
  #         PORT: ${{secrets.PORT}}
  #         SHELL: |                                # add commands i want to execute on server
  #           "cd tests-cicd && ls -a"